### PR TITLE
Make readme slightly kind when deleting a lot of artifacts

### PR DESCRIPTION
**Pull request by banyan**
Thanks for this action! I've reached 2GB and it worked like a charm! I tried re-running right away, but it didn't work, so I added this document.

### CODE REVIEW

**Comment by jeliasson** [comment]
How long did it take for the actual files to be deleted and recognized by GitHub? My builds are still failing.

I run this on `on:push` and don't get any output from the action. Not even a empty `[]`.

```yaml
- name: Deleting old artifacts
   uses: kolpav/purge-artifacts-action@v1
   with:
     token: ${{ secrets.GITHUB_TOKEN }}
     expire-in: 2days
```

**Comment by kolpav** [comment]
@banyan Thank you for PR! I'll get to it soon.

@jeliasson Its hard to tell when github internally reports files as deleted. I find it weird you are not getting any output. Can you take a look at https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging and try setting these `ACTIONS_RUNNER_DEBUG`, `ACTIONS_STEP_DEBUG` secrets to `true`? Action output should then be more verbose It might help you figure out what is wrong.

**Comment by kolpav** [comment]
This is example output taken from successful run of this action
```
2020-03-02T17:17:33.0349074Z ##[group]Run ./
2020-03-02T17:17:33.0349271Z with:
2020-03-02T17:17:33.0349508Z   token: ***
2020-03-02T17:17:33.0349657Z   expire-in: 30minutes
2020-03-02T17:17:33.0349816Z ##[endgroup]
2020-03-02T17:17:33.9719640Z ##[debug]Deleting artifact:
2020-03-02T17:17:33.9719968Z ##[debug]{
2020-03-02T17:17:33.9720220Z ##[debug]  "id": 2399522,
2020-03-02T17:17:33.9720475Z ##[debug]  "node_id": "MDg6QXJ0aWZhY3QyMzk5NTIy",
2020-03-02T17:17:33.9720721Z ##[debug]  "name": "artifact",
2020-03-02T17:17:33.9720981Z ##[debug]  "size_in_bytes": 28,
2020-03-02T17:17:33.9721342Z ##[debug]  "url": "https://api.github.com/repos/kolpav/purge-artifacts-action/actions/artifacts/2399522",
2020-03-02T17:17:33.9721727Z ##[debug]  "archive_download_url": "https://api.github.com/repos/kolpav/purge-artifacts-action/actions/artifacts/2399522/zip",
2020-03-02T17:17:33.9722046Z ##[debug]  "expired": false,
2020-03-02T17:17:33.9722279Z ##[debug]  "created_at": "2020-03-01T21:29:31Z",
2020-03-02T17:17:33.9722540Z ##[debug]  "updated_at": "2020-03-01T21:29:31Z"
2020-03-02T17:17:33.9722835Z ##[debug]}
2020-03-02T17:17:34.1115813Z ::set-output name=deleted-artifacts::[{"id":2399522,"node_id":"MDg6QXJ0aWZhY3QyMzk5NTIy","name":"artifact","size_in_bytes":28,"url":"https://api.github.com/repos/kolpav/purge-artifacts-action/actions/artifacts/2399522","archive_download_url":"https://api.github.com/repos/kolpav/purge-artifacts-action/actions/artifacts/2399522/zip","expired":false,"created_at":"2020-03-01T21:29:31Z","updated_at":"2020-03-01T21:29:31Z"}]
2020-03-02T17:17:34.1116927Z ##[debug]='[{"id":2399522,"node_id":"MDg6QXJ0aWZhY3QyMzk5NTIy","name":"artifact","size_in_bytes":28,"url":"https://api.github.com/repos/kolpav/purge-artifacts-action/actions/artifacts/2399522","archive_download_url":"https://api.github.com/repos/kolpav/purge-artifacts-action/actions/artifacts/2399522/zip","expired":false,"created_at":"2020-03-01T21:29:31Z","updated_at":"2020-03-01T21:29:31Z"}]'
2020-03-02T17:17:34.1244349Z ##[debug]Node Action run completed with exit code 0
```

**Comment by jeliasson** [comment]
@kolpav I can now see `[]` in the debug. However, could you please clarify if it's retroactively deleting artifacts from all branches and it's artifacts or just the one being built on (`on:push` example). I see artifacts created more than 2 days ago on e.g. a release branch. Hopefully it's just lagg.

```
##[debug]Evaluating condition for step: 'Deleting old artifacts'
##[debug]Parsing expression: <success()>
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deleting old artifacts
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run kolpav/purge-artifacts-action@v1
::set-output name=deleted-artifacts::[]
##[debug]='[]'
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Deleting old artifacts
```

**Comment by kolpav** [comment]
@jeliasson Artifacts are tied to repository so yes it is deleting all artifacts per repository.
I know github takes some time to update your usage in billing section of your profile but I don't think it should take long to actually delete the artifacts. I am out of ideas here but I am reasonably sure this action is working I am running it in another private repo where I have two periodical actions one generating artifacts and other (this one) to periodically delete them and it seems to be working fine.


This is action run which generates some garbage artifact just waiting to be deleted, you can see there is none

image

This is another run of same action with artifact yet to be deleted

image

I am using this config
```
name: Delete old artifacts
on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 15min
```

**Comment by kolpav** [comment]
@jeliasson Glad you were able to figure it out 👍

**Comment by jeliasson** [comment]
@kolpav The Billing section still show me 1.1 GB used (0.5 GB included, 0.6 GB over). Still having problems building. I'll give it a few more hours. :)
Also ran the action on the other repository that had a few artifacts, but not close to the amount said on Billing. 

Will keep you updated!

**Comment by kolpav** [comment]
@jeliasson The storage is shared between actions and packages check if packages are not taking up your space.

**Comment by jeliasson** [comment]
> @jeliasson The storage is shared between actions and packages check if packages are not taking up your space.

This GitHub user don't use GitHub Packages, and only have 2 repos that previously had a lot of Artifacts but they are now removed with the help of your Action.

I think this is a bug and that GitHub needs to have a look at it.

**Comment by banyan** [comment]
I had a similar experience in the morning and asked GitHub.

#### Just after I sent this PR: 

image

#### This morning

image

**Comment by jeliasson** [comment]
My have been stuck on 8.2 GB for 12 hours.

image

**Pull request merged**
